export const enUS = {
  tabs: { today: 'Today', food: 'Food', training: 'Training', profile: 'Profile' },
  common: {
    save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', add: 'Add', continue: 'Continue', retry: 'Try again', loading: 'Loading...', saving: 'Saving...', discard: 'Discard', keepEditing: 'Keep editing', saved: 'Saved', notSet: 'Not set', noneAdded: 'None added', close: 'Close', at: 'at', minutesShort: 'min'
  },
  navigation: { planDetails: 'Plan details', healthData: 'Health data', goals: 'Goals', addWorkout: 'Add workout', editWorkout: 'Edit workout' },
  auth: {
    welcomeTitle: 'A calmer way to plan food, training, and recovery.', welcomeMessage: 'Start with a simple profile and get a supportive daily plan built around consistency.', dailyPlanning: 'Daily planning', dailyPlanningMessage: 'Set up your profile and generate a simple plan for food, training, hydration, and recovery.', createAccount: 'Create account', login: 'Log in', welcomeBack: 'Welcome back', loginMessage: 'Log in to continue your daily plan flow.', loggingIn: 'Logging in...', loginFailed: 'Login failed', email: 'Email', password: 'Password', createTitle: 'Create your account', createMessage: 'We use your setup details to create practical, supportive daily guidance.', creatingAccount: 'Creating account...', createFailed: 'Could not create account', existingAccount: 'I already have an account', consent: 'By continuing, you consent to using your profile and preferences to generate your plan.', preparing: 'Getting things ready', checkingSession: 'Checking your session.', loadingSetup: 'Loading your setup', preparingNextStep: 'We are preparing your next step.'
  },
  onboarding: {
    foundationTitle: 'Your foundation', foundationMessage: 'This helps OptiMe keep recommendations age-aware and practical. Safe mode is managed by the backend.', safetyNote: 'Safety note', profileNotSaved: 'Profile was not saved', checkProfile: 'Check your profile', directionTitle: 'Choose your direction', directionMessage: 'Pick the outcome that best matches the season you are in.', safeGoalTitle: "Let's keep this goal safe", checkGoal: 'Check your goal', foodTitle: 'Food preferences', foodMessage: 'Allergy information keeps your first plan safer. The rest can be refined later from Food.', preferencesNotSaved: 'Preferences were not saved', allergyNeededTitle: 'Allergy information needed', allergyNeededMessage: 'Add any food allergies or confirm that you have no known food allergies so we can keep your plan safer.', personalizeTraining: 'Personalize training', personalizeTrainingMessage: 'Optional. You can finish onboarding without this and update it later from Training.', trainingNotSaved: 'Training preferences were not saved', notNow: 'Not now', continueToday: 'Continue to Today'
  },
  today: {
    title: 'Today', tagline: 'Steady, practical, ready.', intro: 'A simple plan for food, training, hydration, and recovery today.', loading: 'Loading Today', loadingMessage: 'Checking whether a plan already exists.', unavailable: 'Today is unavailable', noPlan: 'No plan yet', noPlanMessage: 'Generate a simple plan for food, training, hydration, and recovery today.', generate: 'Generate today plan', generating: 'Generating...', refresh: 'Refresh plan', refreshing: 'Refreshing...', generated: 'Plan generated.', refreshed: 'Plan refreshed', updateFailed: 'Plan update failed', details: 'View plan details', updatedAt: 'Updated {{time}}', safetyNote: 'Safety note', nutrition: 'Nutrition', training: 'Training', recovery: 'Recovery', protein: 'Protein', carbs: 'Carbs', fat: 'Fat', limitReached: 'Limit reached', upgradeSoon: 'Upgrade options coming soon.', planUsage: 'Plan usage', usageUnavailable: 'Plan details unavailable', generationsLeft: 'Generations left today: {{count}}', refreshesLeft: 'Refreshes left today: {{count}}', setupNeeded: 'A little setup is needed', setupNeededMessage: 'Please finish the required basics so we can keep your first plan safe.', continueSetup: 'Continue setup', improvePlans: 'Improve future plans', yourAnswer: 'Your answer', listPlaceholder: 'Separate items with commas', chooseOne: 'Choose one', chooseAny: 'Choose any that fit', answer: 'Answer', skip: 'Skip for now', quickDetail: 'One quick detail', numberNeeded: 'Please enter a number, or skip this for now.', optionNeeded: 'Choose an option, or skip this for now.', optionsNeeded: 'Choose at least one option, or skip this for now.', answerNeeded: 'Add an answer, or skip this for now.', answerSaveFailed: 'Could not save this answer', promptSkipFailed: 'Could not skip this prompt', keepUsingToday: 'You can keep using Today.', limitMessage: "You've reached today's limit for this plan. Your {{plan}} plan includes {{limit}} {{action}} per day. {{reset}}", tryAfter: 'Try again after {{time}}.', tryAfterReset: 'Try again after reset.', usageGeneration: 'plan generation', usageRefresh: 'refresh', usageAiGeneration: 'AI plan generation'
  },
  plan: {
    title: 'Plan details', loading: 'Loading plan', loadingMessage: 'Opening your plan details.', noPlan: 'No plan yet', noPlanMessage: 'Generate a plan from Today to see details here.', meals: 'Meals', mealsHelp: 'How did each meal go? No worries if it changed — this helps us adapt.', trainingCheckIn: 'Training check-in', trainingHelp: 'Tell us what happened. Resting instead is useful signal, not a failure.', pain: 'I felt pain or discomfort', painHelp: 'We will keep future training guidance more conservative when discomfort is reported.', painThanks: "Thanks for letting us know. We'll use this to keep future training guidance more conservative.", checkInThanks: "Thanks, we'll use this to adapt future plans.", checkInFailed: 'Check-in not saved', planStillHere: 'No worries, your plan is still here.', exercises: 'Suggested exercises', targets: 'Targets: {{value}}', equipment: 'Equipment: {{value}}', sets: 'Sets: {{value}}', reps: 'Reps: {{value}}', rest: 'Rest: {{value}}', duration: 'Duration: {{value}}', hydration: 'Hydration', recovery: 'Recovery', reminders: 'Reminders', helpfulQuestion: 'Was this plan helpful?', helpful: 'Helpful', notHelpful: 'Not helpful', sendFeedback: 'Send feedback', feedbackThanks: 'Thanks for the feedback.', feedbackFailed: 'Feedback not saved', chooseRating: 'Choose Helpful or Not helpful first.', statusCompleted: 'Completed', statusPartial: 'Partial', statusSkipped: 'Skipped', statusSwapped: 'Swapped', statusRested: 'Rested', tagTooMuchFood: 'Too much food', tagTooLittleFood: 'Too little food', tagTrainingTooHard: 'Training too hard', tagTrainingTooEasy: 'Training too easy', tagFeltGood: 'Felt good', tagLowEnergy: 'Low energy'
  },
  food: {
    title: 'Food', intro: 'Shape future meal guidance around foods that work for you.', loadingMessage: 'Bringing your saved choices into view.', unavailable: 'Food preferences unavailable', emptyTitle: 'Personalize your meals', emptyMessage: 'Add your dietary preferences and foods you want to avoid to improve future meal recommendations.', setup: 'Set up food preferences', savedMessage: 'Your updated preferences will be used for future plans.', current: 'Current preferences', dietStyle: 'Diet style', mealsPerDay: 'Meals per day', allergies: 'Food allergies', allergiesPlaceholder: 'peanuts, shellfish', noAllergies: 'No known food allergies', noAllergiesHelp: 'Choose this if there are no known food allergies to avoid.', allergyRequired: 'Add allergies or confirm that you have no known food allergies to continue safely.', excludedFoods: 'Excluded foods', excludedPlaceholder: 'foods you prefer to avoid', preferredFoods: 'Preferred foods', preferredPlaceholder: 'rice, eggs, berries', notes: 'Food and meal notes', notesPlaceholder: 'meal timing, simple prep, or other preferences', confirmedNoAllergies: 'No known allergies confirmed'
  },
  training: {
    title: 'Training', intro: 'Set your training focus, available equipment, target muscles, and weekly rhythm.', loadingMessage: 'Checking your preferences and weekly schedule.', unavailable: 'Training setup unavailable', emptyTitle: 'Complete your training setup', emptyMessage: 'Add your environment, equipment, experience level, schedule, and target muscle groups.', setup: 'Set up training', savedMessage: 'Your updated preferences will be used for future plans.', current: 'Current setup', focus: 'Focus', level: 'Level', equipment: 'Equipment', targetMuscles: 'Target muscles', limitations: 'Limitations', trainingFocus: 'Training focus', experienceLevel: 'Experience level', environmentEquipment: 'Environment and equipment', preferredDays: 'Preferred training days', targetHelp: 'Select muscles you want to train. Pain and limitations belong in the separate field below.', limitationsLabel: 'Limitations or pain areas', limitationsPlaceholder: 'Separate items with commas', scheduleHelp: 'Workout type, duration, and frequency are also informed by your weekly schedule below.', preferencesUnavailable: 'Training preferences unavailable', optionalSetup: 'Preparing your optional training setup.'
  },
  schedule: {
    title: 'Training schedule', intro: 'Add a planned session if you have one, or choose a light, safe starting point for today.', loading: 'Loading schedule', loadingMessage: 'Checking your weekly training setup.', unavailable: 'Schedule unavailable', noWorkouts: 'No workouts yet', noWorkoutsMessage: 'Add at least one planned session, or choose no training planned yet.', addWorkout: 'Add workout', editWorkout: 'Edit workout', weekly: 'Weekly schedule', weeklyHelp: 'Workout type and duration live here.', noPlanned: 'No planned workouts yet. Safe defaults remain available.', noTraining: 'No training planned yet', noTrainingHelp: "We'll keep today's training guidance light and safe.", personalize: 'Personalize training (optional)', day: 'Day', time: 'Time', sport: 'Sport', durationMinutes: 'Duration (minutes)', intensity: 'Intensity', description: 'Description', saveWorkout: 'Save workout', saveChanges: 'Save changes', saveFailed: 'Workout was not saved', updateFailed: 'Workout was not updated', deleteFailed: 'Could not delete workout'
  },
  profile: {
    title: 'Profile', sections: { personal: 'Personal', health: 'Health', connections: 'Connections', settings: 'Settings' }, firstName: 'First name', lastName: 'Last name', dateOfBirth: 'Date of birth', datePlaceholder: 'YYYY-MM-DD', height: 'Height ({{unit}})', weight: 'Weight ({{unit}})', gender: 'Gender', activity: 'Activity level', healthContext: 'Optional health context', pregnancyContext: 'Pregnancy / postpartum context', pregnancyHelp: 'Optional. Used only to keep nutrition and training guidance safer.', chooseToday: 'Choose what fits today', preparing: 'Preparing your profile.', unavailable: 'Profile unavailable', savedMessage: 'Personal details saved. Future recommendations will use your updates.', personal: 'Personal', nameMissing: 'Name not added', bornSummary: 'Born {{date}} · {{height}} · {{weight}}', activitySummary: 'Activity: {{value}}', currentGoal: 'Current goal', noGoal: 'No goal saved', goalHelp: 'Goal updates remain owned by the goal resource, not the profile payload.', editGoals: 'Edit goals', addGoals: 'Add goals', wellnessSafety: 'Wellness safety', safeMode: 'Safe mode is active.', standardMode: 'Standard wellness mode is active.', ageSafety: 'Age-aware safety is derived by the backend from your date of birth.', healthContextTitle: 'Health context', healthContextCopy: 'Pregnancy and postpartum context can be updated under Personal when relevant.', important: 'Important'
  },
  goals: {
    title: 'Goals', intro: 'Update the direction OptiMe should consider for future recommendations.', loadingMessage: 'Bringing your saved direction into view.', unavailable: 'Goals unavailable', emptyTitle: 'Set your goals', emptyMessage: 'Add the outcome you want OptiMe to consider when creating future recommendations.', add: 'Add goals', current: 'Current goal', targetSummary: 'Target: {{weight}} · {{days}} days', savedMessage: 'Your updated goals will be used for future plans.', goal: 'Goal', targetWeight: 'Target weight ({{unit}})', timeline: 'Timeline (days)', adjustThrough: 'Adjust through', checkGoal: 'Please review your goal.'
  },
  health: {
    title: 'Health data', intro: 'Optional health summaries can improve future planning. Plan generation still works without them.', providerUnavailable: 'Native health data is unavailable in this build.', status: 'Status', permissions: 'Permissions', connect: 'Connect', connecting: 'Connecting...', manage: 'Manage connection', disconnect: 'Disconnect', disconnecting: 'Disconnecting...', sync: 'Sync now', syncing: 'Syncing...', lastSync: 'Last sync: {{value}}', notSynced: 'Not synced yet', deleteData: 'Delete synced health data', deleting: 'Deleting...', review: 'Review connection explanation', updated: 'Updated', unavailable: 'Health data unavailable', connected: 'Connected', notConnected: 'Not connected', permissionDenied: 'Permission denied', syncError: 'Sync error', explanation: 'You choose what to share. Disconnecting stops future sync; deleting removes imported summaries from OptiMe.', continue: 'Continue', disconnectConfirm: 'Disconnect health data?', deleteConfirm: 'Delete imported health data?', actionCannotUndo: 'This action cannot be undone.', connectionEnabled: '{{provider}} connection is enabled.', disconnectedMessage: '{{provider}} is disconnected. Synced summaries remain until you delete them.', deletedCount: 'Deleted {{count}} synced health summaries.', synced: 'Health summaries synced.', syncedEmpty: 'Health sync completed. No daily summaries were available.', nativeBuildHelp: 'Native sync requires a development build with health support. Expo Go shows a safe unavailable message.', syncHelp: 'OptiMe can request permission for steps, sleep, workouts, and activity, then sync daily summaries for the last 7 days.', syncScope: 'Weight and heart-rate data are not included in this foundation.', beforeConnect: 'Before you connect', manageHelp: 'Disconnecting stops future use. It does not delete stored summaries.'
  },
  bodyMap: {
    front: 'Front', back: 'Back', selected: 'Selected: {{muscles}}', instruction: 'Tap the areas you want your training to emphasize.', select: 'Select {{muscle}} on the {{side}}', deselect: 'Deselect {{muscle}} on the {{side}}', sideLeft: 'left', sideRight: 'right', sideCenter: 'center'
  },
  settings: {
    title: 'Settings', account: 'Account', signedIn: 'Signed in', subscription: 'Subscription', application: 'Application settings', language: 'Language', languageHelp: 'Choose the language used by the application shell.', measurementSystem: 'Measurement system', measurementHelp: 'Choose how measurements are displayed. Stored values remain unchanged.', metric: 'Metric', imperial: 'Imperial', save: 'Save settings', saved: 'Settings updated.', loadError: 'Settings are unavailable right now.', saveError: 'Settings could not be saved.', planUnavailable: 'Plan details unavailable', usageUnavailable: 'Usage details unavailable', usageToday: 'Usage limits are shown on Today when available.', upgradeSoon: 'Upgrade options coming soon.', futureControls: 'Notification controls are planned. No unsaved setting is presented as active.', privacyAccount: 'Privacy and account', privacyCopy: 'Health data management is available under Connections. Account export and deletion remain future settings work.', logout: 'Log out'
  },
  progressive: {
    excludedFoodsTitle: 'Any foods you prefer to avoid?', excludedFoodsDescription: 'We will keep these out of regular suggestions when possible.', preferredFoodsTitle: 'Any foods you want us to use more often?', preferredFoodsDescription: 'A few favorites help future meals feel easier and more familiar.', limitationsTitle: 'Any pain or limitations we should respect?', limitationsDescription: 'Share anything that should keep training guidance gentler or more careful.', equipmentTitle: 'What equipment do you usually have?', equipmentDescription: 'This helps future exercise suggestions fit your real setup.', trainingLevelTitle: 'What is your training level?', trainingLevelDescription: 'This helps keep future exercise guidance realistic.', musclesTitle: 'Any body areas you want to improve?', musclesDescription: 'This will help future training suggestions feel more targeted.', cookingTimeTitle: 'How much cooking time usually fits?', cookingTimeDescription: 'This will help future meals match your day.', mealPrepTitle: 'How do you like to prep meals?', mealPrepDescription: 'This will help future plans feel more practical.', mealTimingTitle: 'Any meal timing preference?', mealTimingDescription: 'This can help future plans work around training and your daily rhythm.', dietTypeTitle: 'Do you follow a diet style?', dietTypeDescription: 'Optional. This helps future meal suggestions fit your preferences.', mealsPerDayTitle: 'How many meals usually fit your day?', mealsPerDayDescription: 'This helps future nutrition guidance match your routine.', trainingOutcomeTitle: 'What do you want training to emphasize?', trainingOutcomeDescription: 'This will help future recommendations lean toward the right style.', options: { VERY_QUICK: 'Very quick', FIFTEEN_TO_THIRTY: '15-30 minutes', LONGER: 'I can cook longer', FRESH: 'Fresh each meal', BATCH_PREP: 'Batch prep', MIXED: 'Mix of both', EARLIER: 'Earlier meals', EVENLY_SPACED: 'Evenly spaced', LATER: 'Later meals', FLEXIBLE: 'Flexible' }
  },
  enums: {
    goalType: { HEALTHY_LIFESTYLE: 'Healthy lifestyle', IMPROVE_FITNESS: 'Improve fitness', BUILD_MUSCLE: 'Build muscle', IMPROVE_ENDURANCE: 'Improve endurance', REDUCE_WEIGHT: 'Reduce weight safely' },
    goalImpact: { NUTRITION_ONLY: 'Nutrition only', NUTRITION_AND_TRAINING: 'Nutrition + training' },
    gender: { female: 'Female', male: 'Male', other: 'Other', prefer_not_to_say: 'Prefer not to say' },
    pregnancyStatus: { NOT_PREGNANT: 'Not pregnant', PREGNANT: 'Pregnant', POSTPARTUM: 'Postpartum', BREASTFEEDING: 'Breastfeeding', PREFER_NOT_TO_SAY: 'Prefer not to say', UNKNOWN: 'Unknown' },
    activityLevel: { LOW: 'Low', LIGHT: 'Light', MODERATE: 'Moderate', HIGH: 'High', ATHLETE: 'Athlete' },
    dietType: { NONE: 'None', OMNIVORE: 'Omnivore', VEGETARIAN: 'Vegetarian', VEGAN: 'Vegan', PESCATARIAN: 'Pescatarian', KETO: 'Keto', LOW_CARB: 'Low carb', MEDITERRANEAN: 'Mediterranean', HALAL: 'Halal', KOSHER: 'Kosher' },
    trainingOutcome: { STRENGTH: 'Strength', MUSCLE_GROWTH: 'Muscle growth', ENDURANCE: 'Endurance', MOBILITY: 'Mobility', GENERAL_FITNESS: 'General fitness' },
    trainingLevel: { BEGINNER: 'Beginner', INTERMEDIATE: 'Intermediate', ADVANCED: 'Advanced' },
    equipment: { GYM: 'Gym', HOME: 'Home', DUMBBELLS: 'Dumbbells', BODYWEIGHT: 'Bodyweight', MACHINES: 'Machines' },
    muscleGroup: { CHEST: 'Chest', TRAPS: 'Traps', LATS: 'Lats', LOWER_BACK: 'Lower back', ABS: 'Abs', OBLIQUES: 'Obliques', BICEPS: 'Biceps', TRICEPS: 'Triceps', FOREARMS: 'Forearms', QUADRICEPS: 'Quadriceps', HAMSTRINGS: 'Hamstrings', ADDUCTORS: 'Adductors', ABDUCTORS: 'Abductors', CALVES: 'Calves', BACK: 'Back', LEGS: 'Legs', GLUTES: 'Glutes', CORE: 'Core', SHOULDERS: 'Shoulders', ARMS: 'Arms', FULL_BODY: 'Full body' },
    sportType: { RUNNING: 'Running', CYCLING: 'Cycling', GYM: 'Gym', STRENGTH: 'Strength', HIIT: 'HIIT', YOGA: 'Yoga', SWIMMING: 'Swimming', WALKING: 'Walking', TEAM_SPORT: 'Team sport', OTHER: 'Other' },
    intensity: { LOW: 'Low', MODERATE: 'Moderate', HIGH: 'High' },
    measurementSystem: { METRIC: 'Metric', IMPERIAL: 'Imperial' },
    healthProvider: { APPLE_HEALTH: 'Apple Health', HEALTH_CONNECT: 'Health Connect' },
    subscriptionPlan: { FREE: 'Free', PLUS: 'Plus', PRO: 'Pro' },
    planQualityMode: { BASIC: 'Basic', PERSONALIZED: 'Personalized', ADAPTIVE: 'Adaptive' },
    readiness: { PUSH: 'Push', MAINTAIN: 'Maintain', RECOVER: 'Recover' },
    weekdays: { sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat' }
  },
  safety: { disclaimer: 'OptiMe is an AI wellness assistant, not a medical service. It does not diagnose or treat medical conditions. For injuries, pregnancy/postpartum concerns, medical symptoms, or major lifestyle changes, consider consulting a qualified professional.', goalSteady: "Let's choose a steadier goal that supports energy, training, and recovery.", goalHealthContext: 'For this health context, OptiMe keeps goals focused on steady energy, recovery, hydration, and balanced habits.', goalProfile: 'Please finish your profile first so we can keep this goal safe and realistic.', goalGeneric: 'Please adjust this goal and try again. We want the plan to stay safe, steady, and practical.' },
  unsaved: { title: 'Discard unsaved changes?', message: 'Your updates have not been saved yet.' },
  errors: { network: 'Something went wrong. Please try again.', validation: 'Please review the information you entered.', required: 'This field is required.', unableLoad: 'Unable to load this information.', unableSave: 'Unable to save your changes.', session: 'Your session has expired. Please log in again.', nativeHealthUnsupported: 'Native health data is not available on this device or build.', invalidSettings: 'Choose a supported language and measurement system.' }
} as const;
