import { createLocaleResource } from './create-locale-resource';

export const zhCN = createLocaleResource({
  tabs: { today: '今日', food: '饮食', training: '训练', profile: '我的' },
  common: { save: '保存', cancel: '取消', edit: '编辑', delete: '删除', add: '添加', continue: '继续', retry: '重试', loading: '加载中…', saving: '保存中…', discard: '放弃更改', keepEditing: '继续编辑', saved: '已保存', notSet: '未设置', noneAdded: '未添加', close: '关闭', at: '于', minutesShort: '分钟' },
  navigation: { planDetails: '计划详情', healthData: '健康数据', goals: '目标', addWorkout: '添加训练', editWorkout: '编辑训练' },
  auth: { welcomeTitle: '更从容地规划饮食、训练与恢复。', welcomeMessage: '完成简单资料，即可获得以稳定习惯为核心的每日计划。', dailyPlanning: '每日规划', dailyPlanningMessage: '设置资料，生成包含饮食、训练、补水和恢复的简单计划。', createAccount: '创建账户', login: '登录', welcomeBack: '欢迎回来', loginMessage: '登录后继续使用每日计划。', loggingIn: '登录中…', loginFailed: '登录失败', email: '邮箱', password: '密码', createTitle: '创建账户', createMessage: '我们会根据你的资料提供实用、友善的每日建议。', creatingAccount: '正在创建账户…', createFailed: '无法创建账户', existingAccount: '我已有账户', consent: '继续即表示你同意使用资料和偏好来生成计划。', preparing: '正在准备', checkingSession: '正在检查登录状态。', loadingSetup: '正在加载设置', preparingNextStep: '正在准备下一步。' },
  onboarding: { foundationTitle: '基础资料', foundationMessage: '这些信息有助于提供符合年龄且实用的建议。安全模式由后端管理。', safetyNote: '安全提示', profileNotSaved: '资料未保存', checkProfile: '请检查资料', directionTitle: '选择方向', directionMessage: '请选择最符合你当前阶段的目标。', safeGoalTitle: '让目标保持安全', checkGoal: '请检查目标', foodTitle: '饮食偏好', foodMessage: '过敏信息能让首个计划更安全，其余内容可稍后完善。', preferencesNotSaved: '偏好未保存', allergyNeededTitle: '需要过敏信息', allergyNeededMessage: '请填写食物过敏，或确认没有已知食物过敏。', personalizeTraining: '个性化训练', personalizeTrainingMessage: '此项可选。你可以先完成引导，之后在“训练”中更新。', trainingNotSaved: '训练偏好未保存', notNow: '暂不设置', continueToday: '前往今日计划' },
  today: { title: '今日', tagline: '稳定、实用、准备就绪。', intro: '今天的饮食、训练、补水与恢复计划。', loading: '正在加载今日计划', loadingMessage: '正在检查是否已有计划。', unavailable: '今日计划暂不可用', noPlan: '还没有计划', noPlanMessage: '生成今天的饮食、训练、补水与恢复计划。', generate: '生成今日计划', generating: '生成中…', refresh: '刷新计划', refreshing: '刷新中…', generated: '计划已生成。', refreshed: '计划已刷新', updateFailed: '计划更新失败', details: '查看计划详情', updatedAt: '更新于 {{time}}', safetyNote: '安全提示', nutrition: '营养', training: '训练', recovery: '恢复', protein: '蛋白质', carbs: '碳水', fat: '脂肪', limitReached: '已达上限', upgradeSoon: '升级选项即将推出。', planUsage: '计划使用情况', usageUnavailable: '使用详情暂不可用', generationsLeft: '今日剩余生成次数：{{count}}', refreshesLeft: '今日剩余刷新次数：{{count}}', setupNeeded: '还需要少量信息', setupNeededMessage: '请完成必要信息，以确保首个计划安全。', continueSetup: '继续设置', improvePlans: '优化后续计划', yourAnswer: '你的回答', listPlaceholder: '请用逗号分隔', chooseOne: '选择一项', chooseAny: '选择所有适用项', answer: '提交回答', skip: '暂时跳过', quickDetail: '补充一个小信息', numberNeeded: '请输入数字，或暂时跳过。', optionNeeded: '请选择一项，或暂时跳过。', optionsNeeded: '请至少选择一项，或暂时跳过。', answerNeeded: '请输入回答，或暂时跳过。', answerSaveFailed: '无法保存回答', promptSkipFailed: '无法跳过此问题', keepUsingToday: '你仍可继续使用今日计划。', limitMessage: '已达到当前方案的今日上限。{{plan}} 方案每天包含 {{limit}} 次{{action}}。{{reset}}', tryAfter: '请在 {{time}} 后重试。', tryAfterReset: '请在重置后重试。', usageGeneration: '计划生成', usageRefresh: '刷新', usageAiGeneration: 'AI 计划生成' },
  plan: { title: '计划详情', loading: '正在加载计划', loadingMessage: '正在打开计划详情。', noPlan: '还没有计划', noPlanMessage: '请先在“今日”中生成计划。', meals: '餐食', mealsHelp: '每餐进行得如何？发生变化也没关系，这会帮助我们调整计划。', trainingCheckIn: '训练打卡', trainingHelp: '告诉我们实际情况。选择休息也是有价值的信息，并非失败。', pain: '我感到疼痛或不适', painHelp: '报告不适后，未来的训练建议会更加保守。', painThanks: '感谢告知。我们会让未来的训练建议更加保守。', checkInThanks: '感谢反馈，我们会据此调整未来计划。', checkInFailed: '打卡未保存', planStillHere: '别担心，你的计划仍然保留。', exercises: '建议动作', targets: '目标肌群：{{value}}', equipment: '器械：{{value}}', sets: '组数：{{value}}', reps: '次数：{{value}}', rest: '休息：{{value}}', duration: '时长：{{value}}', hydration: '补水', recovery: '恢复', reminders: '提醒', helpfulQuestion: '这个计划有帮助吗？', helpful: '有帮助', notHelpful: '没有帮助', sendFeedback: '发送反馈', feedbackThanks: '感谢你的反馈。', feedbackFailed: '反馈未保存', chooseRating: '请先选择“有帮助”或“没有帮助”。', statusCompleted: '已完成', statusPartial: '部分完成', statusSkipped: '已跳过', statusSwapped: '已替换', statusRested: '已休息', tagTooMuchFood: '食物太多', tagTooLittleFood: '食物太少', tagTrainingTooHard: '训练太难', tagTrainingTooEasy: '训练太轻松', tagFeltGood: '感觉良好', tagLowEnergy: '精力不足' },
  food: { title: '饮食', intro: '根据适合你的食物调整未来建议。', loadingMessage: '正在加载已保存的偏好。', unavailable: '饮食偏好暂不可用', emptyTitle: '个性化餐食', emptyMessage: '添加饮食偏好和希望避免的食物，以优化未来建议。', setup: '设置饮食偏好', savedMessage: '更新后的偏好将用于未来计划。', current: '当前偏好', dietStyle: '饮食类型', mealsPerDay: '每日餐数', allergies: '食物过敏', allergiesPlaceholder: '花生、贝类', noAllergies: '没有已知食物过敏', noAllergiesHelp: '如果没有已知食物过敏，请选择此项。', allergyRequired: '请填写过敏信息，或确认没有已知食物过敏。', excludedFoods: '不吃的食物', excludedPlaceholder: '你希望避免的食物', preferredFoods: '偏好的食物', preferredPlaceholder: '米饭、鸡蛋、莓果', notes: '饮食备注', notesPlaceholder: '用餐时间、简单备餐或其他偏好', confirmedNoAllergies: '已确认没有已知过敏' },
  training: { title: '训练', intro: '设置训练重点、可用器械、目标肌群和每周节奏。', loadingMessage: '正在检查偏好和每周安排。', unavailable: '训练设置暂不可用', emptyTitle: '完成训练设置', emptyMessage: '添加训练环境、器械、经验、安排和目标肌群。', setup: '设置训练', savedMessage: '更新后的偏好将用于未来计划。', current: '当前设置', focus: '重点', level: '水平', equipment: '器械', targetMuscles: '目标肌群', limitations: '限制', trainingFocus: '训练目标', experienceLevel: '训练水平', environmentEquipment: '环境与器械', preferredDays: '偏好训练日', targetHelp: '选择希望重点训练的肌群。疼痛和限制请在下方单独填写。', limitationsLabel: '限制或疼痛部位', limitationsPlaceholder: '请用逗号分隔', scheduleHelp: '训练类型、时长和频率也会参考下方的每周安排。', preferencesUnavailable: '训练偏好暂不可用', optionalSetup: '正在准备可选训练设置。' },
  schedule: { title: '训练安排', intro: '添加已计划的训练，或从轻量、安全的方案开始。', loading: '正在加载安排', loadingMessage: '正在检查每周训练安排。', unavailable: '训练安排暂不可用', noWorkouts: '还没有训练', noWorkoutsMessage: '请添加至少一项训练，或选择暂时没有训练计划。', addWorkout: '添加训练', editWorkout: '编辑训练', weekly: '每周安排', weeklyHelp: '训练类型和时长在这里管理。', noPlanned: '还没有计划训练，安全默认建议仍可使用。', noTraining: '暂时没有训练计划', noTrainingHelp: '今天的训练建议会保持轻量和安全。', personalize: '个性化训练（可选）', day: '星期', time: '时间', sport: '运动', durationMinutes: '时长（分钟）', intensity: '强度', description: '说明', saveWorkout: '保存训练', saveChanges: '保存更改', saveFailed: '训练未保存', updateFailed: '训练未更新', deleteFailed: '无法删除训练' },
  profile: { title: '我的', sections: { personal: '个人', health: '健康', connections: '连接', settings: '设置' }, firstName: '名字', lastName: '姓氏', dateOfBirth: '出生日期', datePlaceholder: '年-月-日', height: '身高（{{unit}}）', weight: '体重（{{unit}}）', gender: '性别', activity: '活动水平', healthContext: '可选健康信息', pregnancyContext: '孕期 / 产后情况', pregnancyHelp: '可选，仅用于提高营养和训练建议的安全性。', chooseToday: '选择当前适用项', preparing: '正在准备个人资料。', unavailable: '个人资料暂不可用', savedMessage: '个人资料已保存，将用于未来建议。', personal: '个人资料', nameMissing: '未填写姓名', bornSummary: '出生日期 {{date}} · {{height}} · {{weight}}', activitySummary: '活动水平：{{value}}', currentGoal: '当前目标', noGoal: '未设置目标', goalHelp: '目标与个人资料分别保存。', editGoals: '编辑目标', addGoals: '添加目标', wellnessSafety: '健康安全', safeMode: '安全模式已开启。', standardMode: '标准健康模式已开启。', ageSafety: '后端会根据出生日期应用年龄安全规则。', healthContextTitle: '健康信息', healthContextCopy: '如适用，可在个人资料中更新孕期和产后信息。', important: '重要提示' },
  goals: { title: '目标', intro: '更新 OptiMe 在未来建议中参考的方向。', loadingMessage: '正在加载已保存的目标。', unavailable: '目标暂不可用', emptyTitle: '设置目标', emptyMessage: '添加你希望 OptiMe 在未来建议中考虑的目标。', add: '添加目标', current: '当前目标', targetSummary: '目标：{{weight}} · {{days}} 天', savedMessage: '更新后的目标将用于未来计划。', goal: '目标', targetWeight: '目标体重（{{unit}}）', timeline: '周期（天）', adjustThrough: '调整方式', checkGoal: '请检查目标信息。' },
  health: { title: '健康数据', intro: '可选健康摘要可改善未来规划。没有健康数据也能生成计划。', providerUnavailable: '此版本无法使用原生健康数据。', status: '状态', permissions: '权限', connect: '连接', connecting: '连接中…', manage: '管理连接', disconnect: '断开连接', disconnecting: '正在断开…', sync: '立即同步', syncing: '同步中…', lastSync: '上次同步：{{value}}', notSynced: '尚未同步', deleteData: '删除已同步健康数据', deleting: '删除中…', review: '查看连接说明', updated: '已更新', unavailable: '健康数据暂不可用', connected: '已连接', notConnected: '未连接', permissionDenied: '权限被拒绝', syncError: '同步错误', explanation: '你可以自行选择共享内容。断开连接会停止后续同步，删除会移除导入的摘要。', continue: '继续', disconnectConfirm: '断开健康数据连接？', deleteConfirm: '删除导入的健康数据？', actionCannotUndo: '此操作无法撤销。' },
  bodyMap: { front: '正面', back: '背面', selected: '已选择：{{muscles}}', instruction: '点击希望重点训练的部位。', select: '选择{{side}}{{muscle}}', deselect: '取消选择{{side}}{{muscle}}', sideLeft: '左侧', sideRight: '右侧', sideCenter: '中部' },
  settings: { title: '设置', account: '账户', subscription: '订阅', application: '应用设置', language: '语言', languageHelp: '选择应用界面使用的语言。', measurementSystem: '计量单位', measurementHelp: '选择测量值的显示方式，已存储的数据不会改变。', metric: '公制', imperial: '英制', save: '保存设置', saved: '设置已更新。', loadError: '设置暂不可用。', saveError: '无法保存设置。', planUnavailable: '方案详情暂不可用', usageUnavailable: '使用详情暂不可用', usageToday: '可用限额会显示在“今日”中。', upgradeSoon: '升级选项即将推出。', futureControls: '通知设置将在后续提供。', privacyAccount: '隐私与账户', privacyCopy: '可在“连接”中管理健康数据。', logout: '退出登录' },
  safety: { disclaimer: 'OptiMe 是 AI 健康生活助手，并非医疗服务，不会诊断或治疗疾病。如有受伤、孕期或产后问题、医学症状，或计划进行重大生活方式调整，请考虑咨询合格专业人士。', goalSteady: '让我们选择更稳健的目标，以支持精力、训练与恢复。', goalHealthContext: '在当前健康情况下，OptiMe 会将目标放在稳定精力、恢复、补水和均衡习惯上。', goalProfile: '请先完成个人资料，以便我们保持目标安全且切合实际。', goalGeneric: '请调整目标后重试。我们希望计划保持安全、稳健且实用。' },
  progressive: {
    excludedFoodsTitle: '有哪些食物你希望避免？', excludedFoodsDescription: '我们会尽量不在日常建议中使用这些食物。', preferredFoodsTitle: '有哪些食物你希望更常出现？', preferredFoodsDescription: '加入一些喜欢的食物能让后续餐食更熟悉、更轻松。', limitationsTitle: '有需要注意的疼痛或限制吗？', limitationsDescription: '请告诉我们哪些情况需要让训练建议更温和谨慎。', equipmentTitle: '你通常有哪些训练设备？', equipmentDescription: '这能让后续动作建议更符合你的实际条件。', trainingLevelTitle: '你的训练水平是？', trainingLevelDescription: '这有助于保持后续训练建议切实可行。', musclesTitle: '你希望重点改善哪些身体部位？', musclesDescription: '这会让后续训练建议更有针对性。', cookingTimeTitle: '你通常有多少时间做饭？', cookingTimeDescription: '这会让后续餐食更适合你的日程。', mealPrepTitle: '你喜欢怎样准备餐食？', mealPrepDescription: '这会让后续计划更实用。', mealTimingTitle: '对用餐时间有偏好吗？', mealTimingDescription: '这有助于配合训练和你的日常节奏。', dietTypeTitle: '你遵循某种饮食方式吗？', dietTypeDescription: '可选。这有助于让后续餐食符合你的偏好。', mealsPerDayTitle: '一天通常吃几餐比较合适？', mealsPerDayDescription: '这有助于让营养建议符合你的日常习惯。', trainingOutcomeTitle: '你希望训练重点提升什么？', trainingOutcomeDescription: '这会让后续建议更贴近合适的训练方向。', options: { VERY_QUICK: '非常快', FIFTEEN_TO_THIRTY: '15–30 分钟', LONGER: '可以花更多时间', FRESH: '每餐现做', BATCH_PREP: '集中备餐', MIXED: '两者结合', EARLIER: '较早用餐', EVENLY_SPACED: '均匀间隔', LATER: '较晚用餐', FLEXIBLE: '灵活安排' }
  },
  enums: {
    goalType: { HEALTHY_LIFESTYLE: '保持健康生活', IMPROVE_FITNESS: '提升体能', BUILD_MUSCLE: '增肌', IMPROVE_ENDURANCE: '提升耐力', REDUCE_WEIGHT: '安全减重' }, goalImpact: { NUTRITION_ONLY: '仅调整营养', NUTRITION_AND_TRAINING: '营养与训练' }, gender: { female: '女性', male: '男性', other: '其他', prefer_not_to_say: '不愿透露' }, pregnancyStatus: { NOT_PREGNANT: '未怀孕', PREGNANT: '怀孕', POSTPARTUM: '产后', BREASTFEEDING: '哺乳期', PREFER_NOT_TO_SAY: '不愿透露', UNKNOWN: '未知' }, activityLevel: { LOW: '低', LIGHT: '轻度', MODERATE: '中等', HIGH: '高', ATHLETE: '运动员' }, dietType: { NONE: '无特殊要求', OMNIVORE: '杂食', VEGETARIAN: '素食', VEGAN: '纯素', PESCATARIAN: '鱼素', KETO: '生酮', LOW_CARB: '低碳水', MEDITERRANEAN: '地中海饮食', HALAL: '清真', KOSHER: '犹太洁食' }, trainingOutcome: { STRENGTH: '力量', MUSCLE_GROWTH: '肌肉增长', ENDURANCE: '耐力', MOBILITY: '灵活性', GENERAL_FITNESS: '综合体能' }, trainingLevel: { BEGINNER: '初级', INTERMEDIATE: '中级', ADVANCED: '高级' }, equipment: { GYM: '健身房', HOME: '居家', DUMBBELLS: '哑铃', BODYWEIGHT: '自重', MACHINES: '器械' }, muscleGroup: { CHEST: '胸肌', TRAPS: '斜方肌', LATS: '背阔肌', LOWER_BACK: '下背', ABS: '腹肌', OBLIQUES: '腹斜肌', BICEPS: '肱二头肌', TRICEPS: '肱三头肌', FOREARMS: '前臂', QUADRICEPS: '股四头肌', HAMSTRINGS: '腘绳肌', ADDUCTORS: '内收肌', ABDUCTORS: '外展肌', CALVES: '小腿', BACK: '背部', LEGS: '腿部', GLUTES: '臀肌', CORE: '核心', SHOULDERS: '肩部', ARMS: '手臂', FULL_BODY: '全身' }, sportType: { RUNNING: '跑步', CYCLING: '骑行', GYM: '健身房', STRENGTH: '力量训练', HIIT: '高强度间歇', YOGA: '瑜伽', SWIMMING: '游泳', WALKING: '步行', TEAM_SPORT: '团队运动', OTHER: '其他' }, intensity: { LOW: '低', MODERATE: '中等', HIGH: '高' }, measurementSystem: { METRIC: '公制', IMPERIAL: '英制' }, healthProvider: { APPLE_HEALTH: 'Apple 健康', HEALTH_CONNECT: '健康互联' }, subscriptionPlan: { FREE: '免费', PLUS: 'Plus', PRO: 'Pro' }, planQualityMode: { BASIC: '基础', PERSONALIZED: '个性化', ADAPTIVE: '自适应' }, weekdays: { sun: '周日', mon: '周一', tue: '周二', wed: '周三', thu: '周四', fri: '周五', sat: '周六' }
  },
  unsaved: { title: '放弃未保存的更改？', message: '你的更改尚未保存。' },
  errors: { network: '出现问题，请重试。', validation: '请检查输入的信息。', required: '此项为必填项。', unableLoad: '无法加载此信息。', unableSave: '无法保存更改。', session: '登录已过期，请重新登录。', nativeHealthUnsupported: '此设备或版本不支持原生健康数据。', invalidSettings: '请选择受支持的语言和计量单位。' }
}, {
  health: { connectionEnabled: '已启用 {{provider}} 连接。', disconnectedMessage: '已断开 {{provider}}。同步摘要会保留，直到你将其删除。', deletedCount: '已删除 {{count}} 条健康摘要。', synced: '健康摘要已同步。', syncedEmpty: '健康同步已完成，暂无可用的每日摘要。', nativeBuildHelp: '原生同步需要支持健康数据的开发版本。Expo Go 会显示安全的不可用提示。', syncHelp: 'OptiMe 可请求步数、睡眠、训练和活动权限，并同步最近 7 天的每日摘要。', syncScope: '当前基础版本不包含体重和心率数据。', beforeConnect: '连接前', manageHelp: '断开连接会停止后续使用，但不会删除已保存的摘要。' },
  settings: { signedIn: '已登录' },
  enums: { readiness: { PUSH: '加强', MAINTAIN: '保持', RECOVER: '恢复' } }
}, {
  plan: { foodTab: '饮食', trainingTab: '训练', trainingRecommendation: '今日训练', openExerciseDetails: '打开动作详情', mediaUnavailableCards: '图片暂不可用，动作计划仍可查看。', limitedDetails: '部分旧动作仅提供有限详情。', noExercises: '今天没有安排动作。', exerciseDetailsTitle: '动作详情', exerciseUnavailable: '动作详情不可用', exerciseUnavailableMessage: '当前计划中没有此动作。', imageLoading: '正在加载动作图片', imageUnavailable: '动作图片不可用', mediaPage: '第 {{current}} 张，共 {{total}} 张', planPrescription: '你的计划', prescriptionUnavailable: '请遵循训练建议中的指导。', targetMuscles: '目标肌群', secondaryMuscles: '辅助肌群', equipmentLabel: '器械', noEquipment: '无需器械', aboutExercise: '动作简介', instructions: '动作步骤', coachingCues: '技术提示', safetyNotes: '安全提示', setCount_one: '{{count}} 组', setCount_other: '{{count}} 组' },
  enums: {
    exerciseEquipment: { NONE: '无需器械', BODYWEIGHT: '自重', DUMBBELLS: '哑铃', BARBELL: '杠铃', KETTLEBELL: '壶铃', RESISTANCE_BANDS: '弹力带', MACHINES: '训练器械', BENCH: '训练凳', PULL_UP_BAR: '引体向上杆', CABLE_MACHINE: '绳索器械', CARDIO_MACHINE: '有氧器械' },
    exerciseCategory: { STRENGTH: '力量', MOBILITY: '灵活性', CARDIO: '有氧', RECOVERY: '恢复' },
    movementPattern: { SQUAT: '深蹲', HINGE: '髋部铰链', HORIZONTAL_PUSH: '水平推', VERTICAL_PUSH: '垂直推', HORIZONTAL_PULL: '水平拉', VERTICAL_PULL: '垂直拉', LUNGE: '弓步', CARRY: '负重行走', ROTATION: '旋转', ANTI_ROTATION: '抗旋转', CORE_FLEXION: '核心屈曲', CORE_STABILITY: '核心稳定', ISOLATION: '孤立动作', MOBILITY: '灵活性', CARDIO: '有氧', RECOVERY: '恢复' }
  }
});
