import type { PlanQualityMode } from '@prisma/client';
import type { SupportedLocale } from '@optime/shared-types';

type SummaryCopy = {
  title: string;
  message: string;
  trainingRecommendation: string;
};

export interface MockDailyPlanCopy {
  safeModeReason: string;
  summaries: Record<PlanQualityMode, SummaryCopy>;
  calorieTarget: (kcal: number) => string;
  balancedMeals: string;
  steadyEnergyTarget: string;
  balancedNutritionNotes: string;
  proteinWithEachMeal: string;
  steadyCarbs: string;
  satisfyingFats: string;
  practicalDirection: string;
  hydrationGuidance: string;
  hydrationNotes: string;
  trainingNotes: string;
  controlledSession: string;
  recoveryRecommendation: string;
  sleepTip: string;
  mobilityTip: string;
  reminders: string[];
  breakfast: { name: string; purpose: string; food: string; notes: string };
  lunch: { name: string; purpose: string; food: string; notes: string };
  options: {
    balanced: { label: string; focus: string };
    quick: { label: string; focus: string; breakfast: string; lunch: string; breakfastFood: string; lunchFood: string };
    workout: { label: string; focus: string };
    recovery: { label: string; focus: string; breakfast: string; lunch: string; breakfastFood: string; lunchFood: string };
  };
  exercise: {
    intensityCue: string;
    plannedSession: (minutes: number) => string;
    seconds: (value: number) => string;
    minutes: (value: number) => string;
    easyWalk: { name: string; muscles: string[]; equipment: string[]; duration: string; cue: string; safety: string };
    squat: { name: string; muscles: string[]; equipment: string[]; rest: string; cue: string; safety: string };
    inclinePushUp: { name: string; muscles: string[]; equipment: string[]; rest: string; cue: string; safety: string };
    deadBug: { name: string; muscles: string[]; equipment: string[]; rest: string; cue: string; safety: string };
    gluteBridge: { name: string; muscles: string[]; equipment: string[]; rest: string; cue: string; safety: string };
  };
}

const COPY: Record<SupportedLocale, MockDailyPlanCopy> = {
  'en-US': {
    safeModeReason: 'Safe mode is active for balanced, age-appropriate guidance.',
    summaries: {
      BASIC: { title: 'Steady plan for today', message: "today's plan supports steady energy, balanced meals, and manageable movement.", trainingRecommendation: 'Keep training controlled and sustainable today.' },
      PERSONALIZED: { title: 'Personalized plan for today', message: "today's plan reflects your preferences, schedule, and goal with practical choices.", trainingRecommendation: 'Train in line with your schedule and goal, keeping the session specific but sustainable.' },
      ADAPTIVE: { title: 'Adaptive plan for today', message: "today's plan uses your recent patterns to support steady energy, training, and recovery.", trainingRecommendation: 'Use today as a tailored maintain day, adjusting effort to your recent feedback and schedule.' }
    },
    calorieTarget: (kcal) => `${kcal} kcal target`, balancedMeals: 'Balanced meals', steadyEnergyTarget: 'Steady energy target', balancedNutritionNotes: 'Today focuses on balanced meals, hydration, rest, and healthy movement.', proteinWithEachMeal: 'Protein with each meal', steadyCarbs: 'Choose steady-energy carbs around activity', satisfyingFats: 'Include satisfying fats in moderate portions', practicalDirection: 'Use this as practical direction, not a strict rule.', hydrationGuidance: 'Sip regularly across the day, especially around training.', hydrationNotes: 'Hydration supports energy and recovery.', trainingNotes: 'Adjust effort down if energy, sleep, or recovery feels off.', controlledSession: 'Keep the session controlled today.', recoveryRecommendation: 'Support recovery with regular meals, hydration, and a calm evening routine.', sleepTip: 'Give yourself a realistic wind-down window tonight.', mobilityTip: 'Add gentle mobility if it feels good.', reminders: ['Hydrate regularly', 'Eat after training', 'Keep your evening routine calm'],
    breakfast: { name: 'Breakfast', purpose: 'Start with something familiar, balanced, and easy to repeat.', food: 'Greek yogurt or a preferred protein option', notes: 'Add fruit or oats if that feels good today.' }, lunch: { name: 'Lunch', purpose: 'Midday energy', food: 'Protein, grains, and vegetables', notes: 'Choose foods that match your preferences and allergies.' }, options: { balanced: { label: 'Balanced standard day', focus: 'Steady energy with familiar, practical meals.' }, quick: { label: 'Quick simple prep', focus: 'Easy meals with minimal prep while keeping nutrition steady.', breakfast: 'Simple breakfast', lunch: 'Simple lunch', breakfastFood: 'Protein smoothie', lunchFood: 'Rice bowl with lean protein' }, workout: { label: 'Workout support', focus: 'Meals that support scheduled training and steady recovery.' }, recovery: { label: 'Recovery friendly', focus: 'Gentle, practical meals for an easier recovery-focused day.', breakfast: 'Recovery breakfast', lunch: 'Recovery lunch', breakfastFood: 'Oats with protein', lunchFood: 'Warm grain bowl' } },
    exercise: { intensityCue: 'Keep the movement controlled and leave comfortable effort in reserve.', plannedSession: (minutes) => `Planned for a ${minutes}-minute session with safe pacing.`, seconds: (value) => `${value} seconds`, minutes: (value) => `${value} minutes`, easyWalk: { name: 'Easy walk', muscles: ['full body'], equipment: ['bodyweight'], duration: '10-20 minutes', cue: 'Keep the pace comfortable.', safety: 'Stop or reduce effort if anything feels uncomfortable.' }, squat: { name: 'Bodyweight squat', muscles: ['legs', 'glutes'], equipment: ['bodyweight'], rest: '60-90 seconds', cue: 'Move with control and leave effort in reserve.', safety: 'Use a pain-free range of motion.' }, inclinePushUp: { name: 'Incline push-up', muscles: ['chest', 'shoulders', 'arms'], equipment: ['bench or sturdy surface'], rest: '60-90 seconds', cue: 'Choose an incline that feels smooth and controlled.', safety: 'Skip this if wrists or shoulders feel irritated.' }, deadBug: { name: 'Dead bug', muscles: ['core'], equipment: ['bodyweight'], rest: '45-60 seconds', cue: 'Move slowly and breathe steadily.', safety: 'Keep the movement gentle and controlled.' }, gluteBridge: { name: 'Glute bridge', muscles: ['glutes', 'hamstrings'], equipment: ['bodyweight'], rest: '60 seconds', cue: 'Use a steady pace and stop well before strain.', safety: 'Keep it comfortable for hips and lower back.' } }
  },
  'ru-RU': {
    safeModeReason: 'Безопасный режим активен: рекомендации сбалансированы и подходят для возраста.',
    summaries: {
      BASIC: { title: 'Спокойный план на сегодня', message: 'сегодняшний план поддерживает стабильную энергию, сбалансированное питание и посильную активность.', trainingRecommendation: 'Сохраняйте тренировку контролируемой и устойчивой сегодня.' },
      PERSONALIZED: { title: 'Персональный план на сегодня', message: 'сегодняшний план учитывает ваши предпочтения, расписание и цель.', trainingRecommendation: 'Тренируйтесь в соответствии с расписанием и целью, сохраняя устойчивый темп.' },
      ADAPTIVE: { title: 'Адаптивный план на сегодня', message: 'сегодняшний план учитывает ваши недавние привычки, энергию, тренировку и восстановление.', trainingRecommendation: 'Подстройте нагрузку под недавнюю обратную связь и расписание.' }
    },
    calorieTarget: (kcal) => `Цель: ${kcal} ккал`, balancedMeals: 'Сбалансированное питание', steadyEnergyTarget: 'Ориентир для стабильной энергии', balancedNutritionNotes: 'Сегодня в фокусе сбалансированное питание, вода, отдых и здоровое движение.', proteinWithEachMeal: 'Белок в каждом приёме пищи', steadyCarbs: 'Выбирайте углеводы для стабильной энергии вокруг активности', satisfyingFats: 'Добавляйте сытные жиры умеренно', practicalDirection: 'Это практический ориентир, а не строгое правило.', hydrationGuidance: 'Пейте регулярно в течение дня, особенно вокруг тренировки.', hydrationNotes: 'Вода поддерживает энергию и восстановление.', trainingNotes: 'Снизьте усилие, если энергии, сна или восстановления недостаточно.', controlledSession: 'Сегодня держите тренировку под контролем.', recoveryRecommendation: 'Поддержите восстановление регулярным питанием, водой и спокойным вечером.', sleepTip: 'Оставьте себе реалистичное время для спокойного завершения дня.', mobilityTip: 'Добавьте мягкую подвижность, если это приятно.', reminders: ['Пейте воду регулярно', 'Поешьте после тренировки', 'Сохраните спокойный вечерний ритуал'],
    breakfast: { name: 'Завтрак', purpose: 'Начните с привычного, сбалансированного и простого варианта.', food: 'Греческий йогурт или привычный источник белка', notes: 'Добавьте фрукты или овсянку, если это подходит сегодня.' }, lunch: { name: 'Обед', purpose: 'Энергия в середине дня', food: 'Белок, крупы и овощи', notes: 'Выберите продукты с учётом предпочтений и аллергий.' }, options: { balanced: { label: 'Сбалансированный день', focus: 'Стабильная энергия за счёт привычных практичных блюд.' }, quick: { label: 'Быстро и просто', focus: 'Простые блюда с минимумом подготовки и стабильной энергией.', breakfast: 'Простой завтрак', lunch: 'Простой обед', breakfastFood: 'Белковый смузи', lunchFood: 'Рисовая тарелка с постным белком' }, workout: { label: 'Поддержка тренировки', focus: 'Блюда для запланированной тренировки и ровного восстановления.' }, recovery: { label: 'Для восстановления', focus: 'Мягкие, практичные блюда для дня с фокусом на восстановление.', breakfast: 'Завтрак для восстановления', lunch: 'Обед для восстановления', breakfastFood: 'Овсянка с белком', lunchFood: 'Тёплая зерновая тарелка' } },
    exercise: { intensityCue: 'Двигайтесь контролируемо и оставляйте комфортный запас усилия.', plannedSession: (minutes) => `Запланировано на ${minutes} минут в безопасном темпе.`, seconds: (value) => `${value} сек.`, minutes: (value) => `${value} мин.`, easyWalk: { name: 'Лёгкая ходьба', muscles: ['всё тело'], equipment: ['вес тела'], duration: '10-20 мин.', cue: 'Держите комфортный темп.', safety: 'Остановитесь или снизьте усилие, если появится дискомфорт.' }, squat: { name: 'Приседания с весом тела', muscles: ['ноги', 'ягодицы'], equipment: ['вес тела'], rest: '60-90 сек.', cue: 'Двигайтесь контролируемо и оставляйте запас усилия.', safety: 'Используйте диапазон движения без боли.' }, inclinePushUp: { name: 'Отжимания от опоры', muscles: ['грудь', 'плечи', 'руки'], equipment: ['скамья или устойчивая опора'], rest: '60-90 сек.', cue: 'Выберите высоту, при которой движение остаётся плавным.', safety: 'Пропустите упражнение при дискомфорте в запястьях или плечах.' }, deadBug: { name: 'Мёртвый жук', muscles: ['кор'], equipment: ['вес тела'], rest: '45-60 сек.', cue: 'Двигайтесь медленно и дышите ровно.', safety: 'Сохраняйте мягкое и контролируемое движение.' }, gluteBridge: { name: 'Ягодичный мостик', muscles: ['ягодицы', 'задняя поверхность бедра'], equipment: ['вес тела'], rest: '60 сек.', cue: 'Двигайтесь ровно и остановитесь задолго до перенапряжения.', safety: 'Сохраняйте комфорт для бёдер и поясницы.' } }
  },
  'fr-FR': {
    safeModeReason: 'Le mode de securite est actif avec des conseils equilibres adaptes a votre age.',
    summaries: { BASIC: { title: "Plan regulier pour aujourd'hui", message: "le plan d'aujourd'hui soutient une energie stable, des repas equilibres et un mouvement accessible.", trainingRecommendation: "Gardez l'entrainement controle et durable aujourd'hui." }, PERSONALIZED: { title: "Plan personnalise pour aujourd'hui", message: "le plan d'aujourd'hui tient compte de vos preferences, de votre rythme et de votre objectif.", trainingRecommendation: 'Entrainez-vous selon votre rythme et votre objectif, sans forcer.' }, ADAPTIVE: { title: "Plan adaptatif pour aujourd'hui", message: "le plan d'aujourd'hui utilise vos tendances recentes pour soutenir energie, entrainement et recuperation.", trainingRecommendation: 'Ajustez vos efforts selon vos retours recents et votre planning.' } },
    calorieTarget: (kcal) => `Objectif: ${kcal} kcal`, balancedMeals: 'Repas equilibres', steadyEnergyTarget: "Repere d'energie stable", balancedNutritionNotes: "Aujourd'hui: repas equilibres, hydratation, repos et mouvement sain.", proteinWithEachMeal: 'Proteines a chaque repas', steadyCarbs: "Choisissez des glucides a energie stable autour de l'activite", satisfyingFats: 'Ajoutez des lipides rassasiants avec moderation', practicalDirection: 'Un repere pratique, pas une regle stricte.', hydrationGuidance: "Buvez regulierement pendant la journee, surtout autour de l'entrainement.", hydrationNotes: "L'hydratation soutient l'energie et la recuperation.", trainingNotes: "Reduisez l'effort si l'energie, le sommeil ou la recuperation sont insuffisants.", controlledSession: "Gardez la seance controlee aujourd'hui.", recoveryRecommendation: "Soutenez la recuperation avec des repas reguliers, de l'eau et une soiree calme.", sleepTip: 'Prevoyez un temps realiste pour ralentir ce soir.', mobilityTip: 'Ajoutez de la mobilite douce si cela vous fait du bien.', reminders: ['Hydratez-vous regulierement', "Mangez apres l'entrainement", 'Gardez une routine du soir calme'],
    breakfast: { name: 'Petit-dejeuner', purpose: 'Commencez par quelque chose de familier, equilibre et facile a refaire.', food: 'Yaourt grec ou source de proteines preferee', notes: 'Ajoutez des fruits ou de l avoine si cela vous convient.' }, lunch: { name: 'Dejeuner', purpose: 'Energie de milieu de journee', food: 'Proteines, cereales et legumes', notes: 'Choisissez selon vos preferences et allergies.' }, options: { balanced: { label: 'Journee equilibree', focus: 'Energie stable avec des repas familiers et pratiques.' }, quick: { label: 'Preparation rapide', focus: 'Repas simples avec peu de preparation et une nutrition stable.', breakfast: 'Petit-dejeuner simple', lunch: 'Dejeuner simple', breakfastFood: 'Smoothie proteine', lunchFood: 'Bol de riz avec proteines maigres' }, workout: { label: "Soutien a l'entrainement", focus: "Repas qui soutiennent l'entrainement prevu et une recuperation reguliere." }, recovery: { label: 'Recuperation douce', focus: 'Repas simples et pratiques pour une journee orientee recuperation.', breakfast: 'Petit-dejeuner recuperation', lunch: 'Dejeuner recuperation', breakfastFood: 'Avoine avec proteines', lunchFood: 'Bol de cereales chaud' } },
    exercise: { intensityCue: 'Gardez un mouvement controle avec une marge confortable.', plannedSession: (minutes) => `Prevu pour une seance de ${minutes} minutes a un rythme prudent.`, seconds: (value) => `${value} secondes`, minutes: (value) => `${value} minutes`, easyWalk: { name: 'Marche facile', muscles: ['corps entier'], equipment: ['poids du corps'], duration: '10-20 minutes', cue: 'Gardez une allure confortable.', safety: 'Arretez ou reduisez l effort en cas de gene.' }, squat: { name: 'Squat au poids du corps', muscles: ['jambes', 'fessiers'], equipment: ['poids du corps'], rest: '60-90 secondes', cue: 'Bougez avec controle et gardez une marge.', safety: 'Utilisez une amplitude sans douleur.' }, inclinePushUp: { name: 'Pompe inclinee', muscles: ['poitrine', 'epaules', 'bras'], equipment: ['banc ou support stable'], rest: '60-90 secondes', cue: 'Choisissez une inclinaison fluide et controlee.', safety: 'Passez cet exercice si les poignets ou epaules sont irrites.' }, deadBug: { name: 'Dead bug', muscles: ['centre du corps'], equipment: ['poids du corps'], rest: '45-60 secondes', cue: 'Bougez lentement et respirez regulierement.', safety: 'Gardez le mouvement doux et controle.' }, gluteBridge: { name: 'Pont fessier', muscles: ['fessiers', 'ischio-jambiers'], equipment: ['poids du corps'], rest: '60 secondes', cue: 'Gardez un rythme stable et arretez avant la tension.', safety: 'Gardez le mouvement confortable pour les hanches et le bas du dos.' } }
  },
  'zh-CN': {
    safeModeReason: '安全模式已开启，建议会保持均衡并符合年龄需求。',
    summaries: { BASIC: { title: '今日稳健计划', message: '今天的计划支持稳定能量、均衡饮食和可持续活动。', trainingRecommendation: '今天保持受控且可持续的训练。' }, PERSONALIZED: { title: '今日个性化计划', message: '今天的计划考虑了您的偏好、日程和目标。', trainingRecommendation: '根据日程和目标训练，保持具体但可持续。' }, ADAPTIVE: { title: '今日自适应计划', message: '今天的计划结合近期习惯，支持能量、训练和恢复。', trainingRecommendation: '根据近期反馈和日程调整训练强度。' } },
    calorieTarget: (kcal) => `目标：${kcal} 千卡`, balancedMeals: '均衡饮食', steadyEnergyTarget: '稳定能量目标', balancedNutritionNotes: '今天重点是均衡饮食、补水、休息和健康活动。', proteinWithEachMeal: '每餐包含蛋白质', steadyCarbs: '围绕活动选择稳定供能的碳水', satisfyingFats: '适量加入有饱腹感的脂肪', practicalDirection: '这是实用方向，不是严格规则。', hydrationGuidance: '全天规律饮水，尤其在训练前后。', hydrationNotes: '补水有助于能量和恢复。', trainingNotes: '如果能量、睡眠或恢复状态不佳，请降低强度。', controlledSession: '今天保持受控训练。', recoveryRecommendation: '用规律饮食、补水和平静的晚间习惯支持恢复。', sleepTip: '今晚给自己留出合理的放松时间。', mobilityTip: '感觉良好时可做温和活动。', reminders: ['规律补水', '训练后进餐', '保持平静的晚间习惯'],
    breakfast: { name: '早餐', purpose: '从熟悉、均衡且易重复的选择开始。', food: '希腊酸奶或偏好的蛋白质来源', notes: '如果感觉合适，可加入水果或燕麦。' }, lunch: { name: '午餐', purpose: '午间能量', food: '蛋白质、谷物和蔬菜', notes: '选择符合偏好和过敏需求的食物。' }, options: { balanced: { label: '均衡日', focus: '用熟悉、实用的餐食保持稳定能量。' }, quick: { label: '快速简单准备', focus: '少量准备即可获得稳定营养的简单餐食。', breakfast: '简单早餐', lunch: '简单午餐', breakfastFood: '蛋白质奶昔', lunchFood: '瘦蛋白米饭碗' }, workout: { label: '训练支持', focus: '支持计划训练和稳定恢复的餐食。' }, recovery: { label: '恢复友好', focus: '适合恢复重点日的温和实用餐食。', breakfast: '恢复早餐', lunch: '恢复午餐', breakfastFood: '蛋白燕麦', lunchFood: '热谷物碗' } },
    exercise: { intensityCue: '保持动作受控，并留出舒适的余力。', plannedSession: (minutes) => `计划为 ${minutes} 分钟，以安全节奏完成。`, seconds: (value) => `${value} 秒`, minutes: (value) => `${value} 分钟`, easyWalk: { name: '轻松步行', muscles: ['全身'], equipment: ['自身体重'], duration: '10-20 分钟', cue: '保持舒适节奏。', safety: '如有不适，请停止或降低强度。' }, squat: { name: '徒手深蹲', muscles: ['腿部', '臀部'], equipment: ['自身体重'], rest: '60-90 秒', cue: '受控完成动作，并保留余力。', safety: '使用无痛的动作范围。' }, inclinePushUp: { name: '上斜俯卧撑', muscles: ['胸部', '肩部', '手臂'], equipment: ['长凳或稳固支撑'], rest: '60-90 秒', cue: '选择顺畅且受控的倾斜高度。', safety: '如手腕或肩部不适，请跳过该动作。' }, deadBug: { name: '死虫式', muscles: ['核心'], equipment: ['自身体重'], rest: '45-60 秒', cue: '缓慢移动并平稳呼吸。', safety: '保持温和、受控的动作。' }, gluteBridge: { name: '臀桥', muscles: ['臀部', '腿后侧'], equipment: ['自身体重'], rest: '60 秒', cue: '保持稳定节奏，在用力过度前停止。', safety: '保持臀部和下背部舒适。' } }
  }
};

export function getMockDailyPlanCopy(locale: SupportedLocale): MockDailyPlanCopy {
  return COPY[locale];
}
